
    [[templates]]
        templateName = "Jenkinsfile"
        outputFilePath = "./output/JenkinsFile"
        fileName = "JenkinsFile"
        templatePath = "./MyTemplates"

        [templates.context]
            text = "ApplaudoTest"